name: Deploy
on:
  release:
    types:
      - released
  push:
    branches:
      - main
concurrency: deployment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: intl, mbstring, zip, gd, pdo_mysql, curl, xml, dom, json, opcache, xdebug
          coverage: none
          tools: composer:v2
      - run: composer install
      - run: rsync -rzcEl . root@143.198.179.23:/var/www/html --exclude-from=".rsyncignore" --checksum --delete
      